/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Louisa
 */
public class Tugas_Praktikum_2 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas_Praktikum_2
     */
    public Tugas_Praktikum_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Profil Data XI RPL 5");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 40, 420, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nomer Absen");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 120, 110, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----- Pilih Nomer Urut -----", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(250, 120, 180, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profil Singkat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 0, 14))); // NOI18N

        jTextField3.setEditable(false);

        jTextField2.setEditable(false);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel4.setText("Nama Lengkap");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel5.setText("Nama Panggilan");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3))
                .addGap(345, 345, 345))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 190, 520, 210);

        setBounds(0, 0, 569, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("----- Pilih Nomer Urut -----"))
        {
            jTextField1.setText(" ");
            jTextField2.setText(" ");
            jTextField3.setText(" ");
        }
        else if(jComboBox1.getSelectedItem().equals("1"))
        {
            jTextField1.setText("Ad Reana Vidya Ramadhani");
            jTextField2.setText("Vidya");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("2"))
        {
            jTextField1.setText("Ahmad Devara Alfairus Anindito");
            jTextField2.setText("Devara atau Ahmad");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("3"))
        {
            jTextField1.setText("Alfan Cahyo Wicaksono");
            jTextField2.setText("Alfan");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("4"))
        {
            jTextField1.setText("Anggyanisa Mutia Putri");
            jTextField2.setText("Anggy");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("5"))
        {
            jTextField1.setText("Aulina Roudlotul Jannah");
            jTextField2.setText("Lina");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("6"))
        {
            jTextField1.setText("Ayu Ika Falimatus Zahro");
            jTextField2.setText("Ika");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("7"))
        {
            jTextField1.setText("Bacharuddin Adieb Pratama");
            jTextField2.setText("Adieb");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("8"))
        {
            jTextField1.setText("Bryan Bihza Marsono");
            jTextField2.setText("Bryan");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("9"))
        {
            jTextField1.setText("Danang Prasetya Kalingga");
            jTextField2.setText("Danang");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("10"))
        {
            jTextField1.setText("Erika Prafitasari Rotinsulu");
            jTextField2.setText("Erika");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("11"))
        {
            jTextField1.setText("Fandi Khusnu Pratama");
            jTextField2.setText("Fandi");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("12"))
        {
            jTextField1.setText("Galbie Elinour");
            jTextField2.setText("Galbi");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("13"))
        {
            jTextField1.setText("Iin Nuraini");
            jTextField2.setText("Iin");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("14"))
        {
            jTextField1.setText("Irvina Firadila");
            jTextField2.setText("Irvina");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("15"))
        {
            jTextField1.setText("Jody Mahardika");
            jTextField2.setText("Jody");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("16"))
        {
            jTextField1.setText("Louisa Gabriella");
            jTextField2.setText("Lisa atau Louisa");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("17"))
        {
            jTextField1.setText("M. Taufikur Rohman");
            jTextField2.setText("Taufik");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("18"))
        {
            jTextField1.setText("Mileyanda Qurrota Ayun");
            jTextField2.setText("Yanda");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("19"))
        {
            jTextField1.setText("Monica Briliane Putri");
            jTextField2.setText("Monic");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("20"))
        {
            jTextField1.setText("Muhamad Iqbal Samudra");
            jTextField2.setText("Iqbal");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("21"))
        {
            jTextField1.setText("Multazam Arroihan Gusdiansyah");
            jTextField2.setText("Rehan");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("22"))
        {
            jTextField1.setText("Nabila Febry Indriyanti");
            jTextField2.setText("Febry");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("23"))
        {
            jTextField1.setText("Naufal Dwi Prakoso");
            jTextField2.setText("Naufal");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("24"))
        {
            jTextField1.setText("Nurkumala Budi Fajrin");
            jTextField2.setText("Mala atau Budi");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("25"))
        {
            jTextField1.setText("Pradana Dike Rochmad Izzulhaq");
            jTextField2.setText("Dike");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("26"))
        {
            jTextField1.setText("Prasetya Ananta Wiratama Susanto");
            jTextField2.setText("Nanta");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("27"))
        {
            jTextField1.setText("Ridha Nadhira Febyani");
            jTextField2.setText("Ridha");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("28"))
        {
            jTextField1.setText("Riski Ananda Widiya Putri");
            jTextField2.setText("Kiki");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("29"))
        {
            jTextField1.setText("Sasna Salsabila Hapsari");
            jTextField2.setText("Sasna");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("30"))
        {
            jTextField1.setText("Septy Nur Aulia Sarmantya");
            jTextField2.setText("Septi");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("31"))
        {
            jTextField1.setText("Setiawan Dwi Prasetiyo");
            jTextField2.setText("Wawan");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("32"))
        {
            jTextField1.setText("Sheila Indri Rukmana Putri");
            jTextField2.setText("Sheila");
            jTextField3.setText("Perempuan");
        }else if(jComboBox1.getSelectedItem().equals("33"))
        {
            jTextField1.setText("Siti Afiyah");
            jTextField2.setText("Siti");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("34"))
        {
            jTextField1.setText("Tiara Eka Dehliya");
            jTextField2.setText("Tiara");
            jTextField3.setText("Perempuan");
        }
        else if(jComboBox1.getSelectedItem().equals("35"))
        {
            jTextField1.setText("Tito Maulana");
            jTextField2.setText("Tito");
            jTextField3.setText("Laki-laki");
        }
        else if(jComboBox1.getSelectedItem().equals("36"))
        {
            jTextField1.setText("Vejryn Saviero");
            jTextField2.setText("Vero");
            jTextField3.setText("Laki-laki");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas_Praktikum_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas_Praktikum_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
